[project]
name = "face-tracking"
version = "0.1.0"
description = ""
authors = [
    {name = "gpaull",email = "gavin.m.paull@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python (>=4.10.0,<5.0.0.0)",
    "pandas (>=2.3.0,<3.0.0)",
    "dlib @ file:///Users/gavinpaull/Documents/PycharmProjects/ASC_Data_Processing/SF-TL54/Dlib_Windows_Python3.12-main/dlib-20.0.99-cp312-cp312-macosx_15_0_arm64.whl",
    "mediapipe (>=0.10.21,<0.11.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
